### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by jbschiratti**
Upgrade from scipy 0.19 to scipy >= 1.0. This should fix Travis.
I also removed the exact version requirement for Numpy or Matplotlib.

### CODE REVIEW

**Comment by agramfort** [comment]
One of the ci build should be using our minimal dependency requirement that’s why we had pinned the versions. I am trying now to have a build with minimal requirements and one with latest release

**Comment by jbschiratti** [comment]
Ok I understand. So we may keep `numpy=1.11 matplotlib=1.5` and change `scipy=0.19` for `scipy=1.0`?

**Comment by agramfort** [comment]
We can bump numpy and matplotlib to versions of 2y ago or something? Or copy minimal requirements of mne stable

**Comment by jbschiratti** [comment]
Yes, we can copy the minimal requirements from mne stable.
I do not understand why 2 CI jobs out of 3 have failed. The ones which failed raised `ImportError: cannot import name '_ellipsoid'`. Judging from [this issue](https://github.com/scipy/scipy/issues/8040), this seems to be a problem with the install  of Scipy (conflict between pip and conda?).

**Comment by agramfort** [comment]
thx @jbschiratti I'll continue from there.

**Pull request merged**
